apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-restapp-flask-deployment
  labels:
    app: sample-restapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample-restapp
  template:
    metadata:
      labels:
        app: sample-restapp
    spec:
      containers:
      - name: sample-restapp
        image: dmilan/docker-sample-restapp-flask:r1.01
        ports:
        - containerPort: 8080
