apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-restapp-flask-deployment
  labels:
    app: sample-restapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-restapp
  template:
    metadata:
      labels:
        app: sample-restapp
    spec:
      containers:
      - name: sample-restapp
        image: dmilan/docker-sample-restapp-flask
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-restapp-service-clusterip
spec:
  selector:
    app: sample-restapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
